#!/usr/bin/env node

var output = "",
	begin  = +process.argv[2],
	end    = +process.argv[3];
for (var i = begin; i <= end; i +=1) {
	if (0 === i % 15) {
		output += "fizzbuzz";
	} else if (0 === i % 3) {
		output += "fizz";
	} else if (0 === i % 5) {
		output += "buzz";
	} else {
		output += i;
	}
	output += " ";
}
console.log(output);